### ISSUE TITLE
On Permission state change and resume it force close app

### ISSUE THREAD

**Issue by AmitPrajapati1902** [DMCApps/NavigationFragment#22]
I am facing very big issue in marshmallow, when i am going to change any permission state, and resume that app, it will force close by this error,
do you please help me to resolve it.

```
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.sa_projects, PID: 31201
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sa_projects/com.sa_projects.activity.NavigationDrawerActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.dmcapps.navigationfragment.manager.SingleStackNavigationManagerFragment: make sure class name exists, is public, and has an empty constructor that is public
>    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>    at android.app.ActivityThread.-wrap11(ActivityThread.java)
>    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>    at android.os.Handler.dispatchMessage(Handler.java:102)
>    at android.os.Looper.loop(Looper.java:148)
>    at android.app.ActivityThread.main(ActivityThread.java:5417)
>    at java.lang.reflect.Method.invoke(Native Method)
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.dmcapps.navigationfragment.manager.SingleStackNavigationManagerFragment: make sure class name exists, is public, and has an empty constructor that is public
>    at android.support.v4.app.Fragment.instantiate(Fragment.java:431)
>    at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
>    at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1952)
>    at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:144)
>    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:307)
>    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:81)
>    at com.sa_projects.activity.base.BaseNavigationDrawerActivity.onCreate(BaseNavigationDrawerActivity.java:80)
>    at com.sa_projects.activity.NavigationDrawerActivity.onCreate(NavigationDrawerActivity.java:56)
>    at android.app.Activity.performCreate(Activity.java:6237)
>    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
>    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
>    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>    at android.os.Handler.dispatchMessage(Handler.java:102) 
>    at android.os.Looper.loop(Looper.java:148) 
>    at android.app.ActivityThread.main(ActivityThread.java:5417) 
>    at java.lang.reflect.Method.invoke(Native Method) 
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
> Caused by: java.lang.InstantiationException: java.lang.Class<com.dmcapps.navigationfragment.manager.SingleStackNavigationManagerFragment> has no zero argument constructor
>    at java.lang.Class.newInstance(Native Method)
>    at android.support.v4.app.Fragment.instantiate(Fragment.java:420)
>    at android.support.v4.app.FragmentState.instantiate(Fragment.java:102) 
>    at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1952) 
>    at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:144) 
>    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:307) 
>    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:81) 
>    at com.sa_projects.activity.base.BaseNavigationDrawerActivity.onCreate(BaseNavigationDrawerActivity.java:80) 
>    at com.sa_projects.activity.NavigationDrawerActivity.onCreate(NavigationDrawerActivity.java:56) 
>    at android.app.Activity.performCreate(Activity.java:6237) 
>    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
>    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
>    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>    at android.os.Handler.dispatchMessage(Handler.java:102) 
>    at android.os.Looper.loop(Looper.java:148) 
>    at android.app.ActivityThread.main(ActivityThread.java:5417) 
>    at java.lang.reflect.Method.invoke(Native Method) 
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
> 
```

**Comment by AmitPrajapati1902** [comment]
This is same error as your demo project

**Comment by jjhesk** [comment]
Yes. Same in here..

**Comment by DMCApps** [comment]
Making a hot fix for this issue.

**Comment by DMCApps** [comment]
Version 0.2.0.3 with this hotfix is now live. Please update your dependencies

**Comment by AmitPrajapati1902** [comment]
@DMCApps Thank you very much for resolve this issue. now it working fine.

**Comment by DMCApps** [comment]
@AmitPrajapati1902 awesome glad to hear it's working properly and thanks for using my library!!! I'm starting to put more work into the library so any enhancements please just add them and I'll look at implementing them for you!
